// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiKuS14VotWC7F5Tx_dK6Bap0Uy-Kuqho',
    appId: '1:511758699359:web:a12a9f858e4655687984ea',
    messagingSenderId: '511758699359',
    projectId: 'sampleproject-c84c3',
    authDomain: 'sampleproject-c84c3.firebaseapp.com',
    storageBucket: 'sampleproject-c84c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7i7MafbGutKQ3pVBbMmn_KZG8ZPxUw3k',
    appId: '1:511758699359:android:20b51283e88857ac7984ea',
    messagingSenderId: '511758699359',
    projectId: 'sampleproject-c84c3',
    storageBucket: 'sampleproject-c84c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcHDI4bfdh0hQ2YKyvzCMVmilV-1BvpI',
    appId: '1:511758699359:ios:35c6db9f6c286bed7984ea',
    messagingSenderId: '511758699359',
    projectId: 'sampleproject-c84c3',
    storageBucket: 'sampleproject-c84c3.firebasestorage.app',
    iosBundleId: 'com.example.newSampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiKuS14VotWC7F5Tx_dK6Bap0Uy-Kuqho',
    appId: '1:511758699359:web:dedd7bdc40a418ac7984ea',
    messagingSenderId: '511758699359',
    projectId: 'sampleproject-c84c3',
    authDomain: 'sampleproject-c84c3.firebaseapp.com',
    storageBucket: 'sampleproject-c84c3.firebasestorage.app',
  );
}
